name: churchapp_flutter
description: My ChurchApp Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 10.1.17+17

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_dialog: ^1.1.1
  sqflite: ^2.3.2
  dio: ^4.0.6
  dio_http_cache_lts: ^0.4.1
  provider: ^6.1.1
  transparent_image: ^2.0.1
  fluttertoast:
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  line_awesome_flutter: ^2.0.0
  better_player: ^0.0.83
  youtube_player_flutter: ^9.0.0
  firebase_core: ^2.25.4
  tuple: ^2.0.2
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  email_validator: ^2.1.17
  shimmer: ^3.0.0
  http: ^1.2.0
  audiofileplayer: ^2.1.1
  palette_generator: ^0.3.3+3
  file_utils: ^1.0.1
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  flutter_downloader: ^1.11.6
  in_app_purchase: ^3.1.13
  flutter_share: ^2.0.0
  package_info: ^2.0.2
  launch_review:
  flutter_web_browser: ^0.17.1
  lottie: ^3.1.0
  flutter_widget_from_html: ^0.8.5
  select_dialog: ^2.0.1
  flutter_tts: ^3.8.5
  clipboard: ^0.1.3
  translator: ^1.0.0
  flutter_sticky_header: ^0.6.5
  flutter_material_color_picker: ^1.2.0
  image_picker: ^1.0.7
  lecle_flutter_absolute_path: ^0.0.2+1
  smooth_page_indicator: ^1.1.0
  visibility_detector: ^0.3.3
  file_picker: ^5.2.10
  event_bus: ^2.0.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.5
  photo_view: ^0.14.0
  maps_launcher: ^2.2.0
  video_player: ^2.8.2
  chewie: ^1.5.0
  firebase_analytics: ^10.8.6
  cupertino_icons: ^1.0.6
  super_clipboard: ^0.7.0
  flutter_vlc_player: ^7.4.1
  flutter_advanced_drawer: ^1.3.6
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  pull_to_refresh: ^2.0.0
  collection: ^1.18.0
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  flutter_stripe: ^6.0.0
  just_audio: ^0.9.36
  http_auth: ^1.0.4
  just_audio_background: ^0.0.1-beta.11
  dynamic_text_highlighting:
    git: https://github.com/blakewood84/dynamic_text_highlighting.git

  #  zefyr:
#    git:
#      url: https://github.com/memspace/zefyr.git
#      path: packages/zefyr
#  http: ^0.12.0+1
#  carousel_slider: ^3.0.0
  #flutter_absolute_path: ^1.0.6
  #bottom_navigation_badge: ^1.0.3
  #network_image_to_byte: ^0.0.1
  #apple_sign_in: ^0.1.0
  #toast: ^0.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  slang_build_runner: ^3.1.0

dependency_overrides:
    intl: 0.18.0
    super_native_extensions: any
    wakelock: any
    flutter_quill: ^9.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
